title: Georgia Tech College of Computing Student Council
logo: /assets/img/logo.png
description: Platform for CoC Students to come together and discuss issues concerning the CoC and its future
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
