title: Student Council
logo: /assets/img/logo.png
description: Platform for CoC Students to come together and discuss issues concerning the today and the future of the CoC
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
